Учебный проект: разделяй и властвуй (Часть 1)
htmlacademy-ecmascript/1517989-taskmanager-12 pull request #5
Opened 2020-08-20 21:47 UTC by IOvodov

2020-08-24 17:04 UTC, TeodorDre requested changes

2020-08-24 17:04 UTC, TeodorDre commented on src/view/load-more-button.js
> +    this.element.addEventListener(`click`, this._clickHandler);
Хорошо бы добавить сюда обратно функцию `removeElement()` и перезаписывать ее таким образом, чтобы ты удалял и элемент, и перед этим снял все обработчики с него. (Полезная практика делать это руками, чтобы наверняка)

```
removeElement() {
    this.element.removeEventListener(`click`, this._clickHandler);

    super.removeElement();
  }
```

2020-08-24 17:04 UTC, TeodorDre commented on src/view/load-more-button.js
> +    this.element.addEventListener(`click`, this._clickHandler);
Ты снял обработчик, и потом удалил элемент!

2020-08-24 17:04 UTC, TeodorDre commented on src/view/task-edit.js
> +    this.element.querySelector(`.card__form`).addEventListener(`submit`, this._formSubmitHandler);
Советую все таки выносить выражения `querySelector` в переменные. Длинные выражения никому не нравятся(

```
const formElement = this.element.querySelector(`.card__form`);

formElement.addEventListener(`submit`, this._formSubmitHandler);
```

2020-08-25 21:41 UTC, IOvodov commented on src/utils/render.js
> +export const remove = (component) => {
здесь же используется https://github.com/htmlacademy-ecmascript/1517989-taskmanager-12/pull/5/files#diff-e59ae0b3a774459f5595f99dcedaa573R82

2020-08-28 09:17 UTC, merged